"""Regenerate immutable C tables; semantic tests use archived vendor fixtures."""
from pathlib import Path
import math
import jpeg_codec as jc

def generate():
    lines = ['/* Generated by tests/support/generate_native_tables.py. */']
    for name in ['ZIGZAG','DQT_LUMA_NATURAL','DQT_CHROMA_NATURAL']:
        values = ','.join(map(str,getattr(jc,name)))
        lines.append(f'static const uint8_t {name}[64] = {{{values}}};')
    lines.append('typedef struct { unsigned code, length; } Huffman;')
    for name in ['ENC_DCL','ENC_ACL','ENC_DCC','ENC_ACC']:
        table = getattr(jc,name)
        values = ','.join('{%d,%d}'%table.get(k,(0,0)) for k in range(256))
        lines.append(f'static const Huffman {name}[256] = {{{values}}};')
    rows = []
    for u in range(8):
        rows.append('{'+','.join(format(.5*(1/math.sqrt(2) if u==0 else 1)*
            math.cos((2*x+1)*u*math.pi/16),'.17g') for x in range(8))+'}')
    lines.append('static const double BASIS[8][8] = {'+','.join(rows)+'};')
    return '\n'.join(lines)+'\n'

if __name__ == '__main__':
    root = Path(__file__).resolve().parents[2]
    (root/'App/Sources/CFrameEncoder/Tables.h').write_text(generate())
